platform :ios, '9.3'
target 'magicMenu' do
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'GoogleMaps'
end
